# Generated by Django 2.2.6 on 2019-10-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
